### ISSUE TITLE
from http://stackoverflow.com/questions/1657204/erlang-uuid-generator/1657209#1657209

### ISSUE THREAD

**Issue by mathusiast** [travis/erlang-uuid#1]
I cannot execute v4(): 2> uuid:v4(). *\* exception error: no function clause matching random:uniform(281474976710656.0) in function uuid:v4/0

**Comment by wildchild** [comment]
Check out [this commit](http://github.com/wildchild/erlang-uuid/commit/1df563281bde3ccd0f10d420e1e615f5e3669899)

**Comment by mathusiast** [comment]
this was speedy indeed! thanks on behalf of sinnus (http://stackoverflow.com/users/124411/sinnus)

**Comment by mathusiast** [comment]
.

**Comment by coolchevy** [comment]
fix:
v4() ->
    v4(random:uniform(round(math:pow(2, 48))) - 1, random:uniform(round(math:pow(2, 12))) - 1, random:uniform(round(math:pow(2, 32))) - 1, random:uniform(round(math:pow(2, 30))) - 1).

**Comment by travis** [comment]
should be fixed with jon kristensen's patch
